version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "${WEB_APP_PORTS}:${WEB_APP_PORTS}"
        environment:
            TZ: Asia/Shanghai
        volumes:
            - "/Users/runner/Code:/Users/runner/Code:cached"
            - "./services/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./services/nginx/sites/:/etc/nginx/sites"
    php56:
        build: ./services/php5.6
        volumes:
            - "/Users/runner/Code:/Users/runner/Code:cached"
            - "./services/php5.6/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./services/php5.6/conf.d/docker-php-ext-xhprof.ini:/usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini"
            - "./services/php5.6/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini"
            - "./services/php5.6/php.ini:/usr/local/etc/php/php.ini"
            - "${PHP_PROFILING_PATH}/5.6:/var/www/profiling:delegated"
        environment:
            PHP_XDEBUG_IDEKEY: ${PHP_XDEBUG_IDEKEY}
            PHP_XDEBUG_TRIGGER_KEY: ${PHP_XDEBUG_TRIGGER_KEY}
            PHP_XDEBUG_REMOTE_HOST: ${PHP_XDEBUG_REMOTE_HOST}
            TZ: Asia/Shanghai
        cap_add:
            - SYS_PTRACE
    redis:
        image: redis
        ports:
            - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - redis-data:/data
            - "./services/redis/redis.conf:/usr/local/etc/redis/redis.conf"
        environment:
            TZ: Asia/Shanghai
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./services/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: ""
            TZ: Asia/Shanghai
    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            TZ: Asia/Shanghai
    elasticsearch:
        # image: elasticsearch:6.7.0
        build: ./services/elasticsearch
        # see: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        # see: https://unix.stackexchange.com/questions/449595/meaning-of-the-values-for-ulimit-memlock-flag
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            cluster.name: "runnerdock-cluster"
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            TZ: Asia/Shanghai
    kibana:
        image: kibana:6.7.1
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            TZ: Asia/Shanghai
    
    rabbitmq:
        image: rabbitmq:3.5.1-management
        volumes:
            - "rabbitmq-data:/var/lib/rabbitmq:rw"
            # - "./services/rabbitmqd/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
        ports:
            - 5672:5672
            - 15672:15672
    jaegertracing:
        image: jaegertracing/all-in-one
        ports:
            - 6831:6831/udp
            - 16686:16686

volumes:
    mongo-data:
    mysql-data:
    redis-data:
    elasticsearch-data:
    rabbitmq-data:
