version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - www_data:/home/www-data
            - "./services/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./services/nginx/sites/:/etc/nginx/sites"
            - nginx_log_data:/var/log/nginx
    php56:
        image: runnerlee/php:5.6-fpm
        volumes:
            - www_data:/home/www-data
            - "./services/php5.6/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./services/php5.6/conf.d/docker-php-ext-xhprof.ini:/usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini"
            - "./services/php5.6/php.ini:/usr/local/etc/php/php.ini"
            - php56_profiling_data:/var/www/profiling
        environment:
            PHP_XDEBUG_IDEKEY: ${PHP_XDEBUG_IDEKEY}
            PHP_XDEBUG_TRIGGER_KEY: ${PHP_XDEBUG_TRIGGER_KEY}
    php71:
        image: runnerlee/php:7.1-fpm
        volumes:
            - www_data:/home/www-data
            - "./services/php7.1/php.ini:/usr/local/etc/php/php.ini"
    php72:
        image: runnerlee/php:7.2-fpm
        volumes:
            - www_data:/home/www-data
            - "./services/php7.2/php.ini:/usr/local/etc/php/php.ini"
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./services/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: ""
    elasticsearch:
        image: elasticsearch:6.7.0
        # see: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        # see: https://unix.stackexchange.com/questions/449595/meaning-of-the-values-for-ulimit-memlock-flag
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            cluster.name: "runnerdock-cluster"
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    kibana:
        image: kibana:6.7.0
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch

volumes:
    www_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${WORKSPACE}
    mysql_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${MYSQL_DATA_PATH}
    redis_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${REDIS_DATA_PATH}
    nginx_log_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${NGINX_LOGS_PATH}
    php56_profiling_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PHP_PROFILING_PATH}
    elasticsearch_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${ELASTICSEARCH_DATA_PATH}